from pathlib import Path

p = Path('app/src/main/java/dev/dotclient/android/ui/DotApp.kt')
s = p.read_text()

s = s.replace('import android.app.Activity\nimport android.net.VpnService', 'import android.Manifest\nimport android.app.Activity\nimport android.content.pm.PackageManager\nimport android.net.VpnService\nimport android.os.Build')
s = s.replace('import androidx.activity.result.contract.ActivityResultContracts', 'import androidx.activity.result.contract.ActivityResultContracts\nimport androidx.core.content.ContextCompat')

old = '''    val requestConnect = {\n        when (state.vpnState) {\n            VpnConnectionState.CONNECTED,\n            VpnConnectionState.CONNECTING,\n            VpnConnectionState.DISCONNECTING -> viewModel.disconnect()\n\n            VpnConnectionState.DISCONNECTED,\n            VpnConnectionState.ERROR -> {\n                if (viewModel.requestVpnPermission()) {\n                    val permissionIntent = VpnService.prepare(context)\n                    if (permissionIntent != null) {\n                        vpnPermissionLauncher.launch(permissionIntent)\n                    } else {\n                        viewModel.onVpnPermissionGranted()\n                    }\n                }\n            }\n        }\n    }'''
new = '''    val beginVpnPermissionFlow = {\n        if (viewModel.requestVpnPermission()) {\n            val permissionIntent = VpnService.prepare(context)\n            if (permissionIntent != null) {\n                vpnPermissionLauncher.launch(permissionIntent)\n            } else {\n                viewModel.onVpnPermissionGranted()\n            }\n        }\n    }\n\n    val notificationPermissionLauncher = rememberLauncherForActivityResult(\n        contract = ActivityResultContracts.RequestPermission(),\n    ) {\n        beginVpnPermissionFlow()\n    }\n\n    val requestConnect = {\n        when (state.vpnState) {\n            VpnConnectionState.CONNECTED,\n            VpnConnectionState.CONNECTING,\n            VpnConnectionState.DISCONNECTING -> viewModel.disconnect()\n\n            VpnConnectionState.DISCONNECTED,\n            VpnConnectionState.ERROR -> {\n                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU &&\n                    ContextCompat.checkSelfPermission(context, Manifest.permission.POST_NOTIFICATIONS) != PackageManager.PERMISSION_GRANTED\n                ) {\n                    notificationPermissionLauncher.launch(Manifest.permission.POST_NOTIFICATIONS)\n                } else {\n                    beginVpnPermissionFlow()\n                }\n            }\n        }\n    }'''
if old not in s:
    raise SystemExit('requestConnect block not found')
s = s.replace(old, new)

old_status = '''        Box(\n            modifier = Modifier.size(96.dp).border(1.dp, MaterialTheme.colorScheme.primary, CircleShape),\n            contentAlignment = Alignment.Center,\n        ) {\n            if (state.requestingVpnPermission || state.vpnBusy) {\n                CircularProgressIndicator(\n                    modifier = Modifier.size(34.dp),\n                    strokeWidth = 1.5.dp,\n                    color = MaterialTheme.colorScheme.primary,\n                )\n            } else {\n                Box(\n                    Modifier.size(14.dp).background(\n                        if (state.vpnConnected) MaterialTheme.colorScheme.primary else Color(0xFF7A7A7A),\n                        CircleShape,\n                    )\n                )\n            }\n        }'''
new_status = '''        if (state.themeMode == DotThemeMode.AMOLED) {\n            PixelStatusMatrix(\n                active = state.vpnConnected,\n                busy = state.requestingVpnPermission || state.vpnBusy,\n            )\n        } else {\n            Box(\n                modifier = Modifier.size(96.dp).border(1.dp, MaterialTheme.colorScheme.primary, CircleShape),\n                contentAlignment = Alignment.Center,\n            ) {\n                if (state.requestingVpnPermission || state.vpnBusy) {\n                    CircularProgressIndicator(\n                        modifier = Modifier.size(34.dp),\n                        strokeWidth = 1.5.dp,\n                        color = MaterialTheme.colorScheme.primary,\n                    )\n                } else {\n                    Box(\n                        Modifier.size(14.dp).background(\n                            if (state.vpnConnected) MaterialTheme.colorScheme.primary else Color(0xFF7A7A7A),\n                            CircleShape,\n                        )\n                    )\n                }\n            }\n        }'''
if old_status not in s:
    raise SystemExit('status block not found')
s = s.replace(old_status, new_status)

s = s.replace('''            Text("↓ 0 B", color = Color(0xFF686868), style = MaterialTheme.typography.labelMedium)\n            Text("↑ 0 B", color = Color(0xFF686868), style = MaterialTheme.typography.labelMedium)''', '''            Text(\n                "↓ ${formatRate(state.downloadBytesPerSecond)}",\n                color = Color(0xFF868686),\n                style = MaterialTheme.typography.labelMedium,\n            )\n            Text(\n                "↑ ${formatRate(state.uploadBytesPerSecond)}",\n                color = Color(0xFF868686),\n                style = MaterialTheme.typography.labelMedium,\n            )''')

s = s.replace('''            SettingLine("vpn permission", if (state.vpnPermissionGranted) "granted" else "not requested")\n            SettingLine("app routing", "all apps")\n            SettingLine("dns", "automatic")\n            SettingLine("protocol", "VLESS")''', '''            SettingLine(\n                "status",\n                when (state.vpnState) {\n                    VpnConnectionState.CONNECTED -> "connected"\n                    VpnConnectionState.CONNECTING -> "connecting"\n                    VpnConnectionState.DISCONNECTING -> "disconnecting"\n                    VpnConnectionState.ERROR -> "error"\n                    VpnConnectionState.DISCONNECTED -> "offline"\n                },\n            )\n            SettingLine("protocol", "VLESS")\n            SettingLine("traffic", "realtime")''')

s = s.replace('''private fun SelectedNodeControl(\n    groupName: String,\n    nodeName: String?,\n    onClick: () -> Unit,\n) {\n    Column(\n        modifier = Modifier\n            .fillMaxWidth()\n            .background(Color(0xFF181818), RoundedCornerShape(18.dp))''', '''private fun SelectedNodeControl(\n    groupName: String,\n    nodeName: String?,\n    onClick: () -> Unit,\n) {\n    Column(\n        modifier = Modifier\n            .fillMaxWidth()\n            .background(MaterialTheme.colorScheme.surfaceVariant, RoundedCornerShape(4.dp))''')

insert_before = '\n@Composable\nprivate fun SelectedNodeControl('
pixel_fn = '''\n@Composable\nprivate fun PixelStatusMatrix(active: Boolean, busy: Boolean) {\n    val pattern = listOf(\n        "0011100",\n        "0110110",\n        "1100011",\n        "1000001",\n        "1100011",\n        "0110110",\n        "0011100",\n    )\n    val on = if (active) MaterialTheme.colorScheme.primary else Color(0xFF666666)\n    val off = Color(0xFF151515)\n\n    Column(\n        modifier = Modifier\n            .size(96.dp)\n            .border(1.dp, MaterialTheme.colorScheme.outline, RoundedCornerShape(2.dp))\n            .padding(13.dp),\n        verticalArrangement = Arrangement.spacedBy(3.dp),\n        horizontalAlignment = Alignment.CenterHorizontally,\n    ) {\n        pattern.forEachIndexed { rowIndex, row ->\n            Row(horizontalArrangement = Arrangement.spacedBy(3.dp)) {\n                row.forEachIndexed { colIndex, cell ->\n                    val blink = busy && ((rowIndex + colIndex) % 3 == 0)\n                    Box(\n                        Modifier\n                            .size(7.dp)\n                            .background(if (cell == '1' || blink) on else off)\n                    )\n                }\n            }\n        }\n    }\n}\n'''
if insert_before not in s:
    raise SystemExit('SelectedNodeControl marker not found')
s = s.replace(insert_before, pixel_fn + insert_before, 1)

s += '''\n\nprivate fun formatRate(bytesPerSecond: Long): String {\n    val value = bytesPerSecond.coerceAtLeast(0L).toDouble()\n    return when {\n        value >= 1024.0 * 1024.0 -> String.format("%.1f MB/s", value / (1024.0 * 1024.0))\n        value >= 1024.0 -> String.format("%.0f KB/s", value / 1024.0)\n        else -> "${value.toLong()} B/s"\n    }\n}\n'''

p.write_text(s)

b = Path('app/build.gradle.kts')
g = b.read_text().replace('versionCode = 8', 'versionCode = 9').replace('versionName = "0.0.8"', 'versionName = "0.0.9"')
b.write_text(g)
